In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [ ]:
a = [10,20,30,40]
print(type(a))

<class 'list'>


In [8]:
x = np.array(a)
print(type(x))

<class 'numpy.ndarray'>


In [11]:
a = [1,2,3,4]
b = [10,20,30,40]
x = ([a,b])
print(x)
print(type(x))

[[1, 2, 3, 4], [10, 20, 30, 40]]
<class 'list'>


In [12]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])
print(x)
print(type(x))

[[ 1  2  3  4]
 [10 20 30 40]]
<class 'numpy.ndarray'>


In [18]:
x = np.array([1,2,3,4],dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [19]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [114]:
x = np.ones((3,3,))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
x = np.ones(5,dtype = np.int32)
print(x)
print(type(x))

[1 1 1 1 1]
<class 'numpy.ndarray'>


In [25]:
x = np.random.rand(2,5)
print(x)

[[0.61295518 0.61913837 0.33809669 0.55317204 0.23181581]
 [0.59958512 0.43578841 0.73798771 0.21737607 0.93543688]]


In [27]:
x = np.random.randint(1,20,size = (3,3))
print(x)

[[17 18 18]
 [ 3  7  4]
 [11 19  6]]


In [28]:
x = np.random.randn(2,5)
print(x)

[[-0.8091452  -1.13893691  1.59068496 -0.05013446 -0.59110275]
 [ 1.15049513 -1.13671676 -0.85492259  0.53546252  0.37446482]]


In [29]:
x = np.random.choice([2,3,4,5,6,7,8,])
print(x)

4


In [30]:
x = np.full((3,4),10)
print(x)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [32]:
x = np.ones((3,3))*10
print(x)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [36]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
x = np.eye(4,k=-1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [38]:
x = np.arange(5,11)
print(x)

[ 5  6  7  8  9 10]


In [39]:
x = np.arange(0,11,2)
print(x)

[ 0  2  4  6  8 10]


In [40]:
x = np.linspace(0,1,5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [41]:
x = np.linspace(2,10,5)
print(x)

[ 2.  4.  6.  8. 10.]


In [48]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)
print(x.ndim)
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)
print(y.ndim)

[10 20 30 40 50]
1
[[10 20 30 40 50]
 [ 1  2  3  4  5]]
2


In [50]:
print(y.shape)
print(y.size)

(2, 5)
10


In [57]:
a = np.array([3,6,9,12])
print(a)
print(a.reshape(2,2))

[ 3  6  9 12]
[[ 3  6]
 [ 9 12]]


In [60]:
x = np.arange(1,16)
print(x)
print(x.size)
print(x.reshape(5,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
15
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [65]:
x = np.arange(1,16)
print(x)
y = x.reshape(3,5)
print(y)
z = np.transpose(y)
print(z)
print(y.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [67]:
a = np.arange(1,10)
print(a)
print(a[2:6])

[1 2 3 4 5 6 7 8 9]
[3 4 5 6]


In [70]:
x = np.arange(1,10).reshape(3,3)
print(x)
print(x[1,2])
print(x[1][2])
print(x[1:3,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
6
[[5 6]
 [8 9]]


In [73]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)
x = np.vstack((a,b))
print(x)
x = np.hstack((a,b))
print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [74]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [77]:
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis = 1))
np.concatenate((a,b),axis = 1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [80]:
a = np.arange(10,21,2)
b = np.array([[2],[2]])
print(a)
print(b)
z = a+b
print(z)

[10 12 14 16 18 20]
[[2]
 [2]]
[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [81]:
a = np.arange(10,21,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [82]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [83]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [85]:
a = np.ones((3,3))
b = np.array([2])
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2]


In [87]:
a+b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [88]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [89]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [90]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [91]:
a-1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [92]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [93]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [94]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [96]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
a = np.arange(5,15,2)
print(a)
np.mean(a)

[ 5  7  9 11 13]


np.float64(9.0)

In [98]:
np.median(a)

np.float64(9.0)

In [99]:
np.std(a)

np.float64(2.8284271247461903)

In [100]:
a = np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [101]:
print(np.min(a,axis = 0))

[1 3]


In [102]:
print(np.min(a, axis = 1))

[1 3]


In [103]:
print(np.max(a,axis = 1))

[6 4]


In [104]:
print(np.max(a,axis = 0))

[4 6]


In [107]:
a = np.array([1,4,3,10,20])
x = np.sort(a, kind = 'mergesort')
print(x)

[ 1  3  4 10 20]


In [109]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [110]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [111]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])